-- Seed data: full NeetCode 150 problem catalog
INSERT INTO problem (category, name, sort_order) VALUES ('Arrays & Hashing', 'Contains Duplicate', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Arrays & Hashing', 'Valid Anagram', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Arrays & Hashing', 'Two Sum', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Arrays & Hashing', 'Group Anagrams', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Arrays & Hashing', 'Top K Frequent Elements', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Arrays & Hashing', 'Encode and Decode Strings', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Arrays & Hashing', 'Product of Array Except Self', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Arrays & Hashing', 'Valid Sudoku', 7) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Arrays & Hashing', 'Longest Consecutive Sequence', 8) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Two Pointers', 'Valid Palindrome', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Two Pointers', 'Two Sum II', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Two Pointers', '3Sum', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Two Pointers', 'Container With Most Water', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Two Pointers', 'Trapping Rain Water', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Sliding Window', 'Best Time to Buy and Sell Stock', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Sliding Window', 'Longest Substring Without Repeating Characters', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Sliding Window', 'Longest Repeating Character Replacement', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Sliding Window', 'Permutation in String', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Sliding Window', 'Minimum Window Substring', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Sliding Window', 'Sliding Window Maximum', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Stack', 'Valid Parentheses', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Stack', 'Min Stack', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Stack', 'Evaluate Reverse Polish Notation', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Stack', 'Generate Parentheses', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Stack', 'Daily Temperatures', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Stack', 'Car Fleet', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Stack', 'Largest Rectangle in Histogram', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Binary Search', 'Binary Search', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Binary Search', 'Search a 2D Matrix', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Binary Search', 'Koko Eating Bananas', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Binary Search', 'Find Minimum in Rotated Sorted Array', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Binary Search', 'Search in Rotated Sorted Array', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Binary Search', 'Time Based Key-Value Store', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Binary Search', 'Median of Two Sorted Arrays', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Reverse Linked List', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Merge Two Sorted Lists', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Reorder List', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Remove Nth Node From End of List', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Copy List with Random Pointer', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Add Two Numbers', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Linked List Cycle', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Find the Duplicate Number', 7) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'LRU Cache', 8) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Merge k Sorted Lists', 9) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Linked List', 'Reverse Nodes in k-Group', 10) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Invert Binary Tree', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Maximum Depth of Binary Tree', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Diameter of Binary Tree', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Balanced Binary Tree', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Same Tree', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Subtree of Another Tree', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Lowest Common Ancestor of a BST', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Binary Tree Level Order Traversal', 7) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Binary Tree Right Side View', 8) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Count Good Nodes in Binary Tree', 9) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Validate Binary Search Tree', 10) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Kth Smallest Element in a BST', 11) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Construct Binary Tree from Preorder and Inorder Traversal', 12) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Binary Tree Maximum Path Sum', 13) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Trees', 'Serialize and Deserialize Binary Tree', 14) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Tries', 'Implement Trie', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Tries', 'Design Add and Search Words Data Structure', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Tries', 'Word Search II', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Heap / Priority Queue', 'Kth Largest Element in a Stream', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Heap / Priority Queue', 'Last Stone Weight', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Heap / Priority Queue', 'K Closest Points to Origin', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Heap / Priority Queue', 'Kth Largest Element in an Array', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Heap / Priority Queue', 'Task Scheduler', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Heap / Priority Queue', 'Design Twitter', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Heap / Priority Queue', 'Find Median from Data Stream', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Backtracking', 'Subsets', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Backtracking', 'Combination Sum', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Backtracking', 'Permutations', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Backtracking', 'Subsets II', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Backtracking', 'Combination Sum II', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Backtracking', 'Word Search', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Backtracking', 'Palindrome Partitioning', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Backtracking', 'Letter Combinations of a Phone Number', 7) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Backtracking', 'N-Queens', 8) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Number of Islands', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Max Area of Island', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Clone Graph', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Walls and Gates', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Rotting Oranges', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Pacific Atlantic Water Flow', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Surrounded Regions', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Course Schedule', 7) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Course Schedule II', 8) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Redundant Connection', 9) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Number of Connected Components in an Undirected Graph', 10) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Graph Valid Tree', 11) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Graphs', 'Word Ladder', 12) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Advanced Graphs', 'Reconstruct Itinerary', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Advanced Graphs', 'Min Cost to Connect All Points', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Advanced Graphs', 'Network Delay Time', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Advanced Graphs', 'Swim in Rising Water', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Advanced Graphs', 'Alien Dictionary', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Advanced Graphs', 'Cheapest Flights Within K Stops', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Climbing Stairs', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Min Cost Climbing Stairs', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'House Robber', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'House Robber II', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Longest Palindromic Substring', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Palindromic Substrings', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Decode Ways', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Coin Change', 7) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Maximum Product Subarray', 8) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Word Break', 9) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Longest Increasing Subsequence', 10) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('1-D DP', 'Partition Equal Subset Sum', 11) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Unique Paths', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Longest Common Subsequence', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Best Time to Buy and Sell Stock with Cooldown', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Coin Change II', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Target Sum', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Interleaving String', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Longest Increasing Path in a Matrix', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Distinct Subsequences', 7) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Edit Distance', 8) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Burst Balloons', 9) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('2-D DP', 'Regular Expression Matching', 10) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Greedy', 'Maximum Subarray', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Greedy', 'Jump Game', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Greedy', 'Jump Game II', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Greedy', 'Gas Station', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Greedy', 'Hand of Straights', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Greedy', 'Merge Triplets to Form Target Triplet', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Greedy', 'Partition Labels', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Greedy', 'Valid Parenthesis String', 7) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Intervals', 'Insert Interval', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Intervals', 'Merge Intervals', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Intervals', 'Non-overlapping Intervals', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Intervals', 'Meeting Rooms', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Intervals', 'Meeting Rooms II', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Intervals', 'Minimum Interval to Include Each Query', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Math & Geometry', 'Rotate Image', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Math & Geometry', 'Spiral Matrix', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Math & Geometry', 'Set Matrix Zeroes', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Math & Geometry', 'Happy Number', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Math & Geometry', 'Plus One', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Math & Geometry', 'Pow(x, n)', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Math & Geometry', 'Multiply Strings', 6) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Math & Geometry', 'Detect Squares', 7) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Bit Manipulation', 'Single Number', 0) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Bit Manipulation', 'Number of 1 Bits', 1) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Bit Manipulation', 'Counting Bits', 2) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Bit Manipulation', 'Reverse Bits', 3) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Bit Manipulation', 'Missing Number', 4) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Bit Manipulation', 'Sum of Two Integers', 5) ON CONFLICT (category, name) DO NOTHING;
INSERT INTO problem (category, name, sort_order) VALUES ('Bit Manipulation', 'Reverse Integer', 6) ON CONFLICT (category, name) DO NOTHING;
